---
- hosts: all
  gather_facts: no
  tasks:
  - name: "Install Zabbix repo"
    yum:
      name: "https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm"
      state: latest

  - name: "Install Docker"
    package:
      name: zabbix-agent
      state: latest

  - name: "Enable and start Docker service"
    systemd:
      name: zabbix-agent
      enabled: yes

  - name: "Open Zabbix ports"
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - '10050/tcp'